language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
  - npm run demo:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist/docs
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: dev